services:
  Runway\Console\IApplication:
    class: Runway\Console\Application

  Runway\Console\Input\Parser\IInputParser:
    class: Runway\Console\Input\Parser\InputParser

  Runway\Console\Output\IOutput:
    class: Runway\Console\Output\Output

  Runway\Console\Output\Formatter\IOutputFormatter:
    class: Runway\Console\Output\Formatter\OutputFormatter

  Runway\Console\Output\Table\ITable:
    class: Runway\Console\Output\Table\Table

  Runway\Console\Prompt\IPrompt:
    class: Runway\Console\Prompt\Prompt

  Runway\Console\Command\ListRenderer\ICommandListRenderer:
    class: Runway\Console\Command\ListRenderer\CommandListRenderer
    arguments:
      indent: '%console_commands_list_indent'
